// Stable, time-ordered identifiers for trace events and document entries.
//
// Format: 26-character Crockford-base32 (ULID-style), generated by the
// `ulidx` package (already used by P0's L1Writer).
//
// - Trace ids: `<surface>:<ULID>` — e.g. `edit:01HZK4ABCDEFGHJKMNPQRSTVWX`
// - Entry ids: `m_<ULID>`          — used in the trailing HTML anchor
//
// The ULID's leading 10 characters encode a millisecond timestamp, so
// sorting ids lexically recovers chronological order.

import { ulid } from "ulidx";
import { SURFACES } from "../constants";

// Crockford base32 alphabet excludes I/L/O/U to avoid confusable glyphs.
export const _ENTRY_RE = /^m_[0-9A-HJKMNP-TV-Z]{26}$/;
export const _TRACE_RE = /^[a-z][a-z0-9_-]*:[0-9A-HJKMNP-TV-Z]{26}$/;
// Snapshot ref points at a current workspace entity; the id portion is
// whatever the per-surface adapter chose. Permissive enough to allow an
// embedded `:`, restrictive enough to keep refs safe inside the
// comma-separated footnote serialization.
export const _SNAPSHOT_RE = /^[a-z][a-z0-9_-]*:[A-Za-z0-9_.:\-]+$/;
// L3 surface ref — a bare surface name like `chat`. L3 is a synthesis
// layer that points at L2 *files*, not entries, so its refs carry no id.
// Whitelist (not a loose regex) so `not-an-id` never validates by accident.
// Mirrors SURFACES in constants.ts; add a surface, add it here too.
export const _SHORTNAME_REFS: ReadonlySet<string> = new Set(SURFACES);

export function newEntryId(): string {
  return `m_${ulid()}`;
}

export function newTraceId(surface: string): string {
  return `${surface}:${ulid()}`;
}

export function isEntryId(s: string): boolean {
  return _ENTRY_RE.test(s);
}

export function isTraceId(s: string): boolean {
  return _TRACE_RE.test(s);
}

export function isSnapshotRef(s: string): boolean {
  return _SNAPSHOT_RE.test(s);
}

/** Bare surface name — the form used by L3 refs (whitelist). */
export function isShortnameRef(s: string): boolean {
  return _SHORTNAME_REFS.has(s);
}

/** Any form of ref the ops validator accepts. */
export function isValidRef(s: string): boolean {
  return isEntryId(s) || isTraceId(s) || isSnapshotRef(s) || isShortnameRef(s);
}
